import { defaultLocale, type Locale } from "@/lib/i18n";
import uk from "@/data/i18n/uk/ui.json";
import en from "@/data/i18n/en/ui.json";

// UI chrome — the strings that aren't editorial content: titles, nav labels,
// buttons, the standing disclaimer. Turkish is the source and lives here in
// full; the other locales are generated by scripts/translate.mjs into
// src/data/i18n/<locale>/ui.json and merged over the top.
//
// Anything a locale hasn't got yet falls back to Turkish rather than
// rendering a key or an empty string: a page with three untranslated buttons
// is worth more than a page that says "ui.cta.openAccount".
export const tr = {
  "site.title": "FXPARTNER | Forex Sinyalleri, Piyasa Analizi ve Broker Karşılaştırma",
  "site.description":
    "FXPARTNER; gerçek zamanlı forex sinyalleri, yapay zeka destekli piyasa analizi, teknik/temel analiz ve güvenilir broker karşılaştırmaları sunan finans platformudur.",
  "site.longDescription":
    "FXPARTNER, forex ve finans piyasalarını takip eden yatırımcılar için gerçek zamanlı sinyaller, teknik ve temel analiz, yapay zeka destekli piyasa analizi, ekonomik veri yorumları ve güvenilir broker bilgileriyle kapsamlı bir finans ekosistemi sunar.",
  "nav.signals": "Sinyaller",
  "nav.aiAssistant": "AI Asistan",
  "nav.brokers": "Broker Karşılaştırmaları",
  "nav.blog": "Blog",
  "nav.calendar": "Ekonomik Takvim",
  "nav.more": "Daha Fazla",
  "cta.openAccount": "Hesap Aç",
  "cta.review": "İncele",
  "cta.compare": "Broker Sıralamalarını Gör",
  "label.sponsored": "Sponsorlu",
  "label.contact": "Detaylı Bilgi ve İletişim",
  "disclaimer.short": "Bu içerik genel bilgilendirme amaçlıdır, yatırım tavsiyesi değildir.",
  "disclaimer.risk":
    "Geçmiş sonuçlar gelecekteki sonuçları garanti etmez. Pozisyon büyüklüğünü ve riskini kendi toleransına göre belirle.",
  "language.switch": "Dil",
} as const;

export type UiKey = keyof typeof tr;
export type Dictionary = Record<UiKey, string>;

// Keyed by URL segment: the Ukrainian tree is /ua, its strings are uk.json.
const overlays: Partial<Record<Locale, Record<string, string>>> = { ua: uk, en };

export function getDictionary(locale: Locale): Dictionary {
  if (locale === defaultLocale) return tr;
  const overlay = overlays[locale] ?? {};
  const merged = { ...tr } as Record<string, string>;
  for (const key of Object.keys(tr)) {
    const value = overlay[key];
    if (typeof value === "string" && value.trim()) merged[key] = value;
  }
  return merged as Dictionary;
}

// How much of the chrome a locale actually has, for the coverage report in
// scripts/translate.mjs and for deciding when a tree is worth advertising.
export function dictionaryCoverage(locale: Locale): { translated: number; total: number } {
  const keys = Object.keys(tr);
  if (locale === defaultLocale) return { translated: keys.length, total: keys.length };
  const overlay = overlays[locale] ?? {};
  return {
    translated: keys.filter((k) => typeof overlay[k] === "string" && overlay[k].trim()).length,
    total: keys.length,
  };
}
