import { defaultLocale, type Locale } from "@/lib/i18n";
import uk from "@/data/i18n/uk/ui.json";
import en from "@/data/i18n/en/ui.json";
import ar from "@/data/i18n/ar/ui.json";

// UI chrome — the strings that aren't editorial content: titles, nav labels,
// buttons, the standing disclaimer. Turkish is the source and lives here in
// full; the other locales are generated by scripts/translate.mjs into
// src/data/i18n/<locale>/ui.json and merged over the top.
//
// Anything a locale hasn't got yet falls back to Turkish rather than
// rendering a key or an empty string: a page with three untranslated buttons
// is worth more than a page that says "ui.cta.openAccount".
export const tr = {
  "site.title": "FXPARTNER | Forex Sinyalleri, Piyasa Analizi ve Broker Karşılaştırma",
  "site.description":
    "FXPARTNER; gerçek zamanlı forex sinyalleri, yapay zeka destekli piyasa analizi, teknik/temel analiz ve güvenilir broker karşılaştırmaları sunan finans platformudur.",
  "site.longDescription":
    "FXPARTNER, forex ve finans piyasalarını takip eden yatırımcılar için gerçek zamanlı sinyaller, teknik ve temel analiz, yapay zeka destekli piyasa analizi, ekonomik veri yorumları ve güvenilir broker bilgileriyle kapsamlı bir finans ekosistemi sunar.",
  "nav.signals": "Sinyaller",
  "nav.aiAssistant": "AI Asistan",
  "nav.brokers": "Broker Karşılaştırmaları",
  "nav.blog": "Blog",
  "nav.calendar": "Ekonomik Takvim",
  "nav.more": "Daha Fazla",
  "cta.openAccount": "Hesap Aç",
  "cta.review": "İncele",
  "cta.compare": "Broker Sıralamalarını Gör",
  "label.sponsored": "Sponsorlu",
  "label.contact": "Detaylı Bilgi ve İletişim",
  "disclaimer.short": "Bu içerik genel bilgilendirme amaçlıdır, yatırım tavsiyesi değildir.",
  "disclaimer.risk":
    "Geçmiş sonuçlar gelecekteki sonuçları garanti etmez. Pozisyon büyüklüğünü ve riskini kendi toleransına göre belirle.",
  "language.switch": "Dil",

  // Per-page title and description, extracted from each route's metadata
  // export. These are what a search result actually shows.
  "page.about.title": "Hakkımızda",
  "page.about.description": "FXPARTNER, şeffaf ve dürüst incelemeler aracılığıyla yatırımcıları regüle forex brokerlarıyla buluşturur — ve brokerların gerçek, etkileşimli kitlelerle güven inşa etmesine yardımcı olur.",
  "page.account.register.title": "Ücretsiz Kayıt Ol",
  "page.account.register.description": "FXPARTNER'a ücretsiz üye olun — broker incelemeleri, cashback takibi ve VIP Telegram erişimi.",
  "page.ai-asistan.title": "AI Piyasa Asistanı",
  "page.blacklist.title": "Aracı Kurum Risk Uyarıları",
  "page.blacklist.description": "Düşük bağımsız güven puanları veya yayınlanan incelemelerde tekrarlayan şikayet örüntüleri nedeniyle işaretlenmiş aracı kurumlar.",
  "page.blog.title": "Blog",
  "page.blog.description": "Forex brokerı seçimi, regülasyonun okunması ve işlem maliyetlerinin hesaplanması üzerine rehberler ve açıklayıcı yazılar.",
  "page.broker-lookup.title": "Aracı Kurum Sorgulama",
  "page.broker-lookup.description": "Herhangi bir forex aracı kurumunu isimle arayın ve düzenlenmiş mi, ekstra dikkat gerektiriyor mu, yoksa resmi düzenleyici uyarı listelerinde yüksek riskli olarak mı işaretlenmiş görün.",
  "page.campaigns.title": "Güncel Broker Kampanyaları",
  "page.campaigns.description": "FXPARTNER partner brokerlarının aktif referans ve yatırım kampanyaları, tek bir yerde.",
  "page.cashback.title": "Forex Cashback",
  "page.cashback.description": "İşlem komisyonunuzun bir kısmını geri alın. Hesabınızı katılımcı bir aracı kurumla bağlayın ve kazanç iadenizi FXPARTNER hesabınızdan takip edin.",
  "page.categories.title": "Forex Broker Kategorileri",
  "page.categories.description": "Yeni başlayanlar, düşük spread, yüksek kaldıraç ve daha fazlası — ihtiyacınıza göre forex brokerlarını kategoriye göre keşfedin.",
  "page.complaint.title": "Şikayet Bildir",
  "page.complaint.description": "Bir forex aracı kurumuyla sorun mu yaşadınız? Bize ne olduğunu anlatın, çözüme kavuşturmaya çalışalım.",
  "page.copytrade.title": "Copytrade — FXPARTNER Sinyallerini Otomatik Kopyalayın",
  "page.copytrade.description": "FXPARTNER'ın gerçek, takip edilen MT5 hesabındaki işlemleri kendi hesabınıza otomatik kopyalayan Copier EA — hesabınızın kontrolü her zaman sizde kalır.",
  "page.ekonomik-takvim.title": "Ekonomik Takvim",
  "page.ekonomik-takvim.description": "Canlı ekonomik takvim — CPI, NFP, faiz kararları ve diğer önemli makroekonomik veriler, açıklandığı anda gerçek rakamlarla.",
  "page.haber-bulteni.title": "Haber Bülteni",
  "page.haber-bulteni.description": "Günün öne çıkan finans ve forex piyasası gelişmelerini özgün yorumla derleyen günlük haber bülteni.",
  "page.egitim.gorseller.title": "Görsel Anlatımlar — FXPARTNER Akademi",
  "page.egitim.gorseller.description":
    "Pozisyon büyüklüğü formülü, risk/ödül oranının başabaş eşiği, düşüş telafisi, bekleyen emirlerin fiyata göre yeri, seans saatleri ve kaldıracın teminata etkisi — Akademi derslerinin şekille anlatılan kısmı, tek sayfada.",
  "page.egitim.title": "FXPARTNER Akademi",
  "page.egitim.description":
    "İşlem disiplini, risk yönetimi ve platform mekaniği üzerine yatırımcı eğitim yazıları. Yön tahmini ya da seviye önerisi içermez; yatırım tavsiyesi değildir.",
  "page.instagram.title": "Instagram",
  "page.instagram.description": "@fxpartner_global Instagram hesabından gelenler için giriş sayfası — broker regülasyon sorgusu, günlük teknik analiz bülteni, risk uyarı listesi ve pozisyon hesaplayıcı.",
  "page.app.title": "FXPARTNER Uygulaması",
  "page.app.description":
    "FXPARTNER uygulamasını telefonunuzun veya bilgisayarınızın ana ekranına ekleyin: canlı işlem sinyalleri, anlık bildirimler, ekonomik takvim ve broker karşılaştırma. App Store veya Play Store gerekmez.",
  "page.kurulum.title": "Uygulama Kurulum Rehberi (iOS, Android, Windows)",
  "page.kurulum.description": "FXPARTNER'ı iPhone, Android telefon veya Windows bilgisayarınıza uygulama gibi kurun. Adım adım kurulum rehberi ve bildirimleri açma talimatları.",
  "page.paketler.title": "Paketler",
  "page.paketler.description": "FXPARTNER paketleri — forex sinyalleri ücretsiz üyelikle, GOLD ve endeksler Pro'da, kripto ve enerji VIP'te. Gerçek MT5 hesabından anlık al/sat sinyalleri.",
  "page.partners.title": "Partner Ol",
  "page.partners.description": "FXPARTNER'ın ana IB anlaşması kapsamında bir Sub-IB partner hesabı açın ve yönlendirdiğiniz müşterilerden elde edilen rev-share'den pay alın.",
  "page.piyasa-analizi.title": "Piyasa Analizleri",
  "page.piyasa-analizi.description": "FXPARTNER'ın günlük piyasa özetleri — küresel borsalar, merkez bankası kararları ve ekonomik takvimdeki önemli veriler.",
  "page.pozisyon-hesaplayici.title": "Pozisyon Büyüklüğü Hesaplayıcı",
  "page.pozisyon-hesaplayici.description": "Hesap bakiyeniz, parite ve stop loss mesafenize göre farklı risk seviyelerinde doğru lot büyüklüğünü hesaplayın — canlı piyasa kurlarıyla.",
  "page.privacy.title": "Gizlilik Politikası",
  "page.privacy.description": "FXPARTNER kişisel verilerinizi nasıl toplar, kullanır ve korur.",
  "page.prop-firmalar.indirim-kodlari.description": "Doğrulanmış prop firma kuponları ve challenge ücretinde geçerli indirim oranları.",
  "page.prop-firmalar.description": "Funded hesap veren firmalar, ödeme sicili dahil bağımsız kriterlerle puanlandı.",
  "page.raporlar.forex-broker-duzenleme-raporu.title": "Forex Broker Düzenleme Raporu 2026",
  "page.raporlar.forex-broker-duzenleme-raporu.description": "FXPARTNER'ın kendi verilerine dayanan, güncel olarak hesaplanan forex broker düzenleme kapsamı raporu — tier-1 lisans dağılımı, düzenleyici sıklığı ve kategori kırılımı.",
  "page.signals.title": "Canlı İşlem Sinyalleri",
  "page.teknik-analiz.title": "Teknik Analiz",
  "page.teknik-analiz.description": "FXPARTNER'ın gün içi teknik analiz bültenleri — gerçek grafikler, pivot seviyeleri, destek/direnç bantları ve RSI/MACD yorumlarıyla.",
  "page.terms.title": "Kullanım Şartları",
  "page.terms.description": "fxpartner.global kullanımına ilişkin şartlar.",
  "page.topluluk.title": "Topluluk",
  "page.topluluk.description": "FXPARTNER'ın küresel yatırımcı topluluğu — gerçek broker yorumları, piyasa beklenti anketi ve resmi Telegram/X kanalları.",
  "page.ai-asistan.description": "Yatırımcıların tercih ettiği FXPARTNER Piyasa Asistanı — forex, altın, CPI/NFP gibi makro veriler ve teknik/temel analiz stratejileri hakkında sorularınızı yanıtlar.",
  "page.signals.description": "Takip edilen MT5 hesabımızdan gerçek işlem sinyalleri — açık işlemler için giriş, kâr al ve zarar durdur seviyeleri, ayrıca her işlem kapandığında doğrulanmış kazanç/kayıp sonuçları.",
  "page.brokerlar.title": "{year} En İyi Forex Brokerleri — Karşılaştırma ve Bağımsız Puanlama",
  "page.brokerlar.description": "{count} forex brokeri regülasyon, işlem maliyeti, platform ve para çekme deneyimi üzerinden bağımsız olarak puanlandı. Aracı kurum karşılaştırması, gerçek kullanıcı yorumları ve risk uyarıları.",
  "page.prop-firmalar.title": "{year} En İyi Prop Firmaları — Funded Hesap Karşılaştırması",
  "page.prop-firmalar.indirim-kodlari.title": "Prop Firma İndirim Kodları {year} — Güncel ve Doğrulanmış",
} as const;

export type UiKey = keyof typeof tr;
export type Dictionary = Record<UiKey, string>;

// Keyed by URL segment: the Ukrainian tree is /ua, its strings are uk.json.
const overlays: Partial<Record<Locale, Record<string, string>>> = { ua: uk, en, ar };

export function getDictionary(locale: Locale): Dictionary {
  if (locale === defaultLocale) return tr;
  const overlay = overlays[locale] ?? {};
  const merged = { ...tr } as Record<string, string>;
  for (const key of Object.keys(tr)) {
    const value = overlay[key];
    if (typeof value === "string" && value.trim()) merged[key] = value;
  }
  return merged as Dictionary;
}

// How much of the chrome a locale actually has, for the coverage report in
// scripts/translate.mjs and for deciding when a tree is worth advertising.
export function dictionaryCoverage(locale: Locale): { translated: number; total: number } {
  const keys = Object.keys(tr);
  if (locale === defaultLocale) return { translated: keys.length, total: keys.length };
  const overlay = overlays[locale] ?? {};
  return {
    translated: keys.filter((k) => typeof overlay[k] === "string" && overlay[k].trim()).length,
    total: keys.length,
  };
}
