import { defaultLocale, type Locale } from "@/lib/i18n";
import type { Broker } from "@/data/brokers";
import type { BlogPost } from "@/data/blog";
import ukBrokers from "@/data/i18n/uk/brokers.json";
import enBrokers from "@/data/i18n/en/brokers.json";
import ukBlog from "@/data/i18n/uk/blog.json";
import enBlog from "@/data/i18n/en/blog.json";

// Editorial content stays authored once, in Turkish, in src/data. The
// translations are flat key/value overlays generated by
// scripts/translate.mjs and applied here on read, so a page never has to
// know which language it is rendering — it asks for the broker or post it
// always asked for, in the locale it happens to be in.
//
// Every field falls back to the Turkish original when the overlay has no
// entry: a broker added today shows up in all three trees immediately,
// Turkish until it is translated, rather than blank.

type Overlay = Record<string, string>;

const brokerOverlays: Partial<Record<Locale, Overlay>> = { ua: ukBrokers, en: enBrokers };
const blogOverlays: Partial<Record<Locale, Overlay>> = { ua: ukBlog, en: enBlog };

function pick(overlay: Overlay, key: string, fallback: string): string {
  const value = overlay[key];
  return typeof value === "string" && value.trim() ? value : fallback;
}

function pickList(overlay: Overlay, prefix: string, fallback: string[]): string[] {
  return fallback.map((item, i) => pick(overlay, `${prefix}.${i}`, item));
}

export function localizeBroker(broker: Broker, locale: Locale): Broker {
  if (locale === defaultLocale) return broker;
  const o = brokerOverlays[locale];
  if (!o) return broker;
  const s = broker.slug;

  return {
    ...broker,
    tagline: pick(o, `${s}.tagline`, broker.tagline),
    summary: pick(o, `${s}.summary`, broker.summary),
    bestFor: pick(o, `${s}.bestFor`, broker.bestFor),
    accentNote: pick(o, `${s}.accentNote`, broker.accentNote),
    pros: pickList(o, `${s}.pros`, broker.pros),
    cons: pickList(o, `${s}.cons`, broker.cons),
    extraFaqs: broker.extraFaqs?.map((faq, i) => ({
      q: pick(o, `${s}.faq.${i}.q`, faq.q),
      a: pick(o, `${s}.faq.${i}.a`, faq.a),
    })),
    deepDive: broker.deepDive && {
      ...broker.deepDive,
      deposits: pick(o, `${s}.deepDive.deposits`, broker.deepDive.deposits),
      withdrawals: pick(o, `${s}.deepDive.withdrawals`, broker.deepDive.withdrawals),
      support: pick(o, `${s}.deepDive.support`, broker.deepDive.support),
      education: pick(o, `${s}.deepDive.education`, broker.deepDive.education),
    },
  };
}

export function localizeBrokers(list: Broker[], locale: Locale): Broker[] {
  if (locale === defaultLocale) return list;
  return list.map((b) => localizeBroker(b, locale));
}

export function localizeBlogPost(post: BlogPost, locale: Locale): BlogPost {
  if (locale === defaultLocale) return post;
  const o = blogOverlays[locale];
  if (!o) return post;
  const s = post.slug;

  return {
    ...post,
    title: pick(o, `${s}.title`, post.title),
    excerpt: pick(o, `${s}.excerpt`, post.excerpt),
    sections: post.sections.map((section, i) => ({
      ...section,
      heading: section.heading ? pick(o, `${s}.s${i}.heading`, section.heading) : section.heading,
      paragraphs: section.paragraphs.map((p, j) => pick(o, `${s}.s${i}.p${j}`, p)),
      list: section.list?.map((item, j) => pick(o, `${s}.s${i}.l${j}`, item)),
    })),
  };
}

export function localizeBlogPosts(list: BlogPost[], locale: Locale): BlogPost[] {
  if (locale === defaultLocale) return list;
  return list.map((p) => localizeBlogPost(p, locale));
}

// Share of a content set that a locale actually has, for reporting.
export function contentCoverage(locale: Locale): { brokers: number; blog: number } {
  const count = (o?: Overlay) => (o ? Object.values(o).filter((v) => v && v.trim()).length : 0);
  return { brokers: count(brokerOverlays[locale]), blog: count(blogOverlays[locale]) };
}
