import { defaultLocale, type Locale } from "@/lib/i18n";
import { translateChrome } from "@/lib/chrome";
import { getServerLocale } from "@/lib/serverLocale";
import type { Broker } from "@/data/brokers";
import type { BlogPost } from "@/data/blog";
import ukBrokers from "@/data/i18n/uk/brokers.json";
import enBrokers from "@/data/i18n/en/brokers.json";
import ukBlog from "@/data/i18n/uk/blog.json";
import enBlog from "@/data/i18n/en/blog.json";
import arBrokers from "@/data/i18n/ar/brokers.json";
import arBlog from "@/data/i18n/ar/blog.json";

// Editorial content stays authored once, in Turkish, in src/data. The
// translations are flat key/value overlays generated by
// scripts/translate.mjs and applied here on read, so a page never has to
// know which language it is rendering — it asks for the broker or post it
// always asked for, in the locale it happens to be in.
//
// Every field falls back to the Turkish original when the overlay has no
// entry: a broker added today shows up in all three trees immediately,
// Turkish until it is translated, rather than blank.

type Overlay = Record<string, string>;

const brokerOverlays: Partial<Record<Locale, Overlay>> = { ua: ukBrokers, en: enBrokers, ar: arBrokers };
const blogOverlays: Partial<Record<Locale, Overlay>> = { ua: ukBlog, en: enBlog, ar: arBlog };

function pick(overlay: Overlay, key: string, fallback: string): string {
  const value = overlay[key];
  return typeof value === "string" && value.trim() ? value : fallback;
}

function pickList(overlay: Overlay, prefix: string, fallback: string[]): string[] {
  return fallback.map((item, i) => pick(overlay, `${prefix}.${i}`, item));
}

export function localizeBroker(broker: Broker, locale: Locale): Broker {
  if (locale === defaultLocale) return broker;
  const o = brokerOverlays[locale];
  if (!o) return broker;
  const s = broker.slug;

  return {
    ...broker,
    tagline: pick(o, `${s}.tagline`, broker.tagline),
    summary: pick(o, `${s}.summary`, broker.summary),
    bestFor: pick(o, `${s}.bestFor`, broker.bestFor),
    accentNote: pick(o, `${s}.accentNote`, broker.accentNote),
    promotion: broker.promotion && {
      ...broker.promotion,
      tag: pick(o, `${s}.promo.tag`, broker.promotion.tag),
      title: pick(o, `${s}.promo.title`, broker.promotion.title),
      intro: pick(o, `${s}.promo.intro`, broker.promotion.intro),
    },
    pros: pickList(o, `${s}.pros`, broker.pros),
    cons: pickList(o, `${s}.cons`, broker.cons),
    extraFaqs: broker.extraFaqs?.map((faq, i) => ({
      q: pick(o, `${s}.faq.${i}.q`, faq.q),
      a: pick(o, `${s}.faq.${i}.a`, faq.a),
    })),
    deepDive: broker.deepDive && {
      ...broker.deepDive,
      deposits: pick(o, `${s}.deepDive.deposits`, broker.deepDive.deposits),
      withdrawals: pick(o, `${s}.deepDive.withdrawals`, broker.deepDive.withdrawals),
      support: pick(o, `${s}.deepDive.support`, broker.deepDive.support),
      education: pick(o, `${s}.deepDive.education`, broker.deepDive.education),
    },
  };
}

/**
 * Overlay first, catalogue second.
 *
 * localizeBroker() names the fields it translates, which means a field added
 * to the Broker type after it was written renders Turkish and nothing says
 * so — forty-four strings on the review pages were doing exactly that. The
 * walk catches whatever the named list missed, translating by the Turkish
 * string itself, and leaves anything neither knows about as the Turkish it
 * already was.
 *
 * Order matters: the per-slug overlay is the better translation (a human can
 * fix "xm.summary" without touching any other broker), so it wins where it
 * exists.
 */
export function localizeBrokerDeep(broker: Broker, locale: Locale): Broker {
  return localizeData(localizeBroker(broker, locale), locale);
}

export function localizeBrokers(list: Broker[], locale: Locale): Broker[] {
  if (locale === defaultLocale) return list;
  return list.map((b) => localizeBrokerDeep(b, locale));
}

export function localizeBlogPost(post: BlogPost, locale: Locale): BlogPost {
  if (locale === defaultLocale) return post;
  const o = blogOverlays[locale];
  if (!o) return post;
  const s = post.slug;

  return {
    ...post,
    title: pick(o, `${s}.title`, post.title),
    excerpt: pick(o, `${s}.excerpt`, post.excerpt),
    sections: post.sections.map((section, i) => ({
      ...section,
      heading: section.heading ? pick(o, `${s}.s${i}.heading`, section.heading) : section.heading,
      paragraphs: section.paragraphs.map((p, j) => pick(o, `${s}.s${i}.p${j}`, p)),
      list: section.list?.map((item, j) => pick(o, `${s}.s${i}.l${j}`, item)),
    })),
  };
}

export function localizeBlogPosts(list: BlogPost[], locale: Locale): BlogPost[] {
  if (locale === defaultLocale) return list;
  return list.map((p) => localizeBlogPost(p, locale));
}

// Structural keys: their values are identifiers, not prose. Translating a
// slug would break a route, and translating an icon name would break a
// lookup, so the walk steps over them without looking.
const STRUCTURAL_KEYS = new Set([
  "slug", "href", "id", "icon", "key", "type", "src", "url", "code",
  "logo", "image", "color", "variant", "group", "path", "locale", "pair",
  "affiliateUrl", "trackingUrl", "email", "phone",
  // Values used as lookup keys or enum members, not shown as prose. These
  // became dangerous the moment the copy test stopped requiring a Turkish
  // diacritic: broker.categories holds "Beginners" and "Low Spread", which
  // read as English copy but are the keys categoryInfo is indexed by —
  // translating them made every broker card throw.
  "categories", "category", "segment", "segments", "models", "platforms",
  "regulators", "status", "outcome", "tier", "verdict", "unit",
  "drawdownUnit", "direction", "scope", "role",
  "symbol", "ticker", "currency", "date", "updatedAt", "publishedAt",
]);

/**
 * Translates every prose leaf of a Turkish-authored data tree.
 *
 * The five remaining data modules — prop firms, market and technical
 * analysis, package tiers, the partner program — each have their own shape,
 * and giving each one a localizeX() with its own key scheme would be five
 * schemes to keep in sync with five files. They do not need one: tr() is
 * keyed by the Turkish string itself, so the catalogue can be reached by
 * walking the structure and looking up each leaf. No key naming, no drift,
 * and a new field is translated the moment someone adds its string to the
 * dictionary.
 *
 * Untranslated leaves come back as the Turkish they already were, which is
 * the same fallback every other surface has.
 */
export function localizeData<T>(value: T, locale: Locale): T {
  if (locale === defaultLocale) return value;
  return walk(value, locale) as T;
}

function walk(value: unknown, locale: Locale): unknown {
  if (typeof value === "string") return translateChrome(locale, value);
  if (Array.isArray(value)) return value.map((item) => walk(item, locale));
  if (value && typeof value === "object" && Object.getPrototypeOf(value) === Object.prototype) {
    const out: Record<string, unknown> = {};
    for (const [key, item] of Object.entries(value)) {
      out[key] = STRUCTURAL_KEYS.has(key) ? item : walk(item, locale);
    }
    return out;
  }
  // Numbers, booleans, dates, class instances — nothing to translate, and
  // rebuilding them would lose their identity.
  return value;
}

/**
 * Server-side companion to localizeData(), reading the locale the page
 * recorded for this request. Same relationship tr() has to translateChrome():
 * the caller does not repeat the locale it already established.
 */
export function trData<T>(value: T): T {
  return localizeData(value, getServerLocale());
}

// Share of a content set that a locale actually has, for reporting.
export function contentCoverage(locale: Locale): { brokers: number; blog: number } {
  const count = (o?: Overlay) => (o ? Object.values(o).filter((v) => v && v.trim()).length : 0);
  return { brokers: count(brokerOverlays[locale]), blog: count(blogOverlays[locale]) };
}
