import type { Metadata } from "next";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { cashbackPrograms } from "@/data/cashback";
import { getBrokerBySlug } from "@/data/brokers";

export const metadata: Metadata = {
  title: "Forex Cashback",
  description:
    "Get part of your trading commission back. Link your account with a participating broker and track your cashback from your FXPARTNER account.",
  alternates: { canonical: "/cashback" },
};

export default function CashbackPage() {
  return (
    <>
      <Header />
      <main className="flex-1 bg-paper-high">
        <section className="bg-ink text-text-on-ink">
          <div className="mx-auto max-w-3xl px-6 py-16 md:py-20">
            <span className="font-mono text-xs uppercase tracking-[0.25em] text-gold">
              Cashback
            </span>
            <h1 className="mt-4 font-poppins text-4xl font-semibold leading-[1.1] tracking-tight md:text-5xl">
              Get part of your trading cost back
            </h1>
            <p className="mt-5 max-w-xl text-lg leading-relaxed text-text-on-ink-muted">
              When you trade with a broker through our partner link, the
              broker pays us a share of the commission generated by your
              trading volume. We pass part of that back to you, paid
              directly into your trading account by the broker.
            </p>
            <p className="mt-5 max-w-xl text-sm leading-relaxed text-text-on-ink-muted">
              Pick a broker below, submit your trading account number, and
              we&apos;ll confirm it against our partner records — no account
              required. Rates below are current estimates and may be
              adjusted once final terms with each broker are confirmed.
            </p>
          </div>
        </section>

        <section>
          <div className="mx-auto max-w-3xl px-6 py-16">
            <div className="divide-y divide-hairline-light border-t border-hairline-light">
              {cashbackPrograms.map((program) => {
                const broker = getBrokerBySlug(program.brokerSlug);
                if (!broker) return null;
                return (
                  <div key={program.brokerSlug} className="py-6">
                    <div className="flex flex-wrap items-baseline justify-between gap-3">
                      <h2 className="font-poppins text-xl font-semibold text-text-dark">
                        {broker.name}
                      </h2>
                      <span className="font-mono text-sm font-semibold text-gold">
                        {program.rateLabel}
                      </span>
                    </div>
                    <p className="mt-2 text-sm text-text-muted">{program.rateNote}</p>
                    <div className="mt-3 flex flex-wrap gap-4">
                      <Link
                        href={`/cashback/${broker.slug}/setup`}
                        className="font-mono text-xs uppercase tracking-[0.15em] text-signal transition-colors hover:text-signal-strong"
                      >
                        Get Cashback →
                      </Link>
                      <Link
                        href={`/brokers/${broker.slug}`}
                        className="font-mono text-xs uppercase tracking-[0.15em] text-text-muted transition-colors hover:text-text-dark"
                      >
                        Full review →
                      </Link>
                    </div>
                  </div>
                );
              })}
            </div>

            <div className="mt-14 rounded-2xl border border-hairline-light bg-paper p-6">
              <h3 className="font-poppins text-lg font-semibold text-text-dark">
                Ready to link your account?
              </h3>
              <p className="mt-2 text-sm leading-relaxed text-text-muted">
                Sign in to your FXPARTNER account to submit your trading
                account number and track your cashback history.
              </p>
              <Link
                href="/account/login"
                className="mt-4 inline-block rounded-full bg-ink px-5 py-2.5 text-sm font-medium text-text-on-ink transition-colors hover:bg-ink-soft"
              >
                Sign In / Link Account
              </Link>
            </div>

            <p className="mt-8 text-xs leading-relaxed text-text-muted">
              Cashback is paid directly to your trading account by the
              broker, based on your real trading volume. Amounts shown on
              your account page are recorded manually from our partner
              dashboard, not generated automatically, and may take time to
              reflect recent activity. This is not investment advice.
            </p>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
