import type { Metadata } from "next";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import PartnerApplicationForm from "@/components/PartnerApplicationForm";
import { cashbackPrograms } from "@/data/cashback";
import { getBrokerBySlug } from "@/data/brokers";

export const metadata: Metadata = {
  title: "Become a Partner",
  description:
    "Open a Sub-IB partner account under FXPARTNER's master IB agreement and earn a share of the rev-share generated by clients you refer.",
  alternates: { canonical: "/partners" },
};

const steps = [
  {
    title: "Apply",
    body: "Tell us about your audience and how you plan to introduce them to a broker. No cost, no commitment.",
  },
  {
    title: "We connect you with the broker",
    body: "We introduce you to the broker's partner desk as a Sub-IB under our existing master IB agreement, so you don't have to negotiate terms from scratch.",
  },
  {
    title: "Get your own partner link",
    body: "Once approved by the broker, you receive your own tracking link and partner dashboard, separate from ours.",
  },
  {
    title: "Earn on real trading volume",
    body: "You earn your agreed share of the rev-share generated by the volume of clients who sign up through your link and trade.",
  },
];

export default function PartnersPage() {
  const eligibleBrokers = cashbackPrograms
    .map((p) => getBrokerBySlug(p.brokerSlug))
    .filter((b): b is NonNullable<typeof b> => Boolean(b));

  return (
    <>
      <Header />
      <main className="flex-1 bg-paper-high">
        <section className="bg-ink text-text-on-ink">
          <div className="mx-auto max-w-3xl px-6 py-16 md:py-20">
            <span className="font-mono text-xs uppercase tracking-[0.25em] text-gold">
              Partner Program
            </span>
            <h1 className="mt-4 font-poppins text-4xl font-semibold leading-[1.1] tracking-tight md:text-5xl">
              Become a partner, not just an investor
            </h1>
            <p className="mt-5 max-w-xl text-lg leading-relaxed text-text-on-ink-muted">
              If you have an audience, community, or network of traders, you
              don&apos;t have to trade to earn with FXPARTNER. Open your own
              Sub-IB (sub-introducing broker) account with our partner
              brokers under our master IB agreement, and earn a share of the
              revenue generated by the clients you bring in.
            </p>
            <p className="mt-5 max-w-xl text-sm leading-relaxed text-text-on-ink-muted">
              This is separate from our{" "}
              <Link href="/cashback" className="text-gold hover:underline">
                cashback program
              </Link>
              , which is for people trading their own account. This program is
              for people who want to build a referral business around forex
              brokers.
            </p>
            <a
              href="#apply"
              className="mt-8 inline-block rounded-full bg-signal px-6 py-3 text-sm font-medium text-paper-high transition-colors hover:bg-signal-strong"
            >
              Apply as a Partner
            </a>
          </div>
        </section>

        <section>
          <div className="mx-auto max-w-3xl px-6 py-16">
            <h2 className="font-poppins text-2xl font-semibold text-text-dark">
              How it works
            </h2>
            <div className="mt-8 grid gap-6 sm:grid-cols-2">
              {steps.map((step, i) => (
                <div
                  key={step.title}
                  className="rounded-2xl border border-hairline-light bg-paper p-6"
                >
                  <span className="font-mono text-xs uppercase tracking-[0.2em] text-signal">
                    Step {i + 1}
                  </span>
                  <h3 className="mt-2 font-poppins text-lg font-semibold text-text-dark">
                    {step.title}
                  </h3>
                  <p className="mt-2 text-sm leading-relaxed text-text-muted">
                    {step.body}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="bg-paper">
          <div className="mx-auto max-w-3xl px-6 py-16">
            <h2 className="font-poppins text-2xl font-semibold text-text-dark">
              Brokers with an active partner agreement
            </h2>
            <p className="mt-3 max-w-xl text-sm leading-relaxed text-text-muted">
              Sub-IB partnerships are currently available for the brokers
              below, where FXPARTNER already has a confirmed master IB
              agreement in place. Let us know your preference in the
              application — we&apos;ll confirm feasibility and exact terms
              with the broker directly.
            </p>
            <div className="mt-8 divide-y divide-hairline-light border-t border-hairline-light">
              {eligibleBrokers.map((broker) => (
                <div key={broker.slug} className="flex flex-wrap items-baseline justify-between gap-3 py-5">
                  <h3 className="font-poppins text-lg font-semibold text-text-dark">
                    {broker.name}
                  </h3>
                  <Link
                    href={`/brokers/${broker.slug}`}
                    className="font-mono text-xs uppercase tracking-[0.15em] text-text-muted transition-colors hover:text-text-dark"
                  >
                    Full review →
                  </Link>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section>
          <div className="mx-auto max-w-3xl px-6 py-16">
            <h2 className="font-poppins text-2xl font-semibold text-text-dark">
              Who this is for
            </h2>
            <ul className="mt-6 space-y-3 text-sm leading-relaxed text-text-muted">
              <li>— You run a social media account, YouTube channel, or blog with an audience interested in trading.</li>
              <li>— You manage a trading signal group, community, or Telegram channel.</li>
              <li>— You already refer traders informally and want a proper, trackable partner setup instead.</li>
              <li>— You run a business or network where forex broker referrals are a natural fit.</li>
            </ul>
            <p className="mt-6 text-xs leading-relaxed text-text-muted">
              This is not investment advice, and it is not a guaranteed income
              opportunity — actual earnings depend entirely on the trading
              volume of clients you refer and each broker&apos;s final
              approval and terms. FXPARTNER does not accept applications
              intended to spam, mislead, or misrepresent the broker to
              potential clients.
            </p>
          </div>
        </section>

        <section id="apply" className="bg-paper scroll-mt-20">
          <div className="mx-auto max-w-2xl px-6 py-16">
            <h2 className="font-poppins text-2xl font-semibold text-text-dark">
              Apply as a partner
            </h2>
            <p className="mt-3 text-sm leading-relaxed text-text-muted">
              Fill in the form below and our partnerships team will follow up
              by email.
            </p>
            <div className="mt-8">
              <PartnerApplicationForm
                brokers={eligibleBrokers.map((b) => ({ slug: b.slug, name: b.name }))}
              />
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
