import type { Metadata } from "next";
import Link from "next/link";
import Footer from "@/components/Footer";
import Reveal from "@/components/Reveal";
import TiltWrapper from "@/components/TiltWrapper";
import PartnerApplicationForm from "@/components/PartnerApplicationForm";
import PartnerDashboardPreview from "@/components/PartnerDashboardPreview";
import PartnerSmoothScroll from "@/components/partners/PartnerSmoothScroll";
import PartnerHero from "@/components/partners/PartnerHero";
import StepTimeline from "@/components/partners/StepTimeline";
import CommissionCalculator from "@/components/partners/CommissionCalculator";
import PartnerTierCards from "@/components/partners/PartnerTierCards";
import WhyFxPartner from "@/components/partners/WhyFxPartner";
import ContentStudioPreview from "@/components/partners/ContentStudioPreview";
import ContentLibraryTeaser from "@/components/partners/ContentLibraryTeaser";
import GlobalNetworkMap from "@/components/partners/GlobalNetworkMap";
import PartnerFAQ from "@/components/partners/PartnerFAQ";
import { cashbackPrograms } from "@/data/cashback";
import { getBrokerBySlug, brokers } from "@/data/brokers";

export const metadata: Metadata = {
  title: "Become a Partner",
  description:
    "Open a Sub-IB partner account under FXPARTNER's master IB agreement and earn a share of the rev-share generated by clients you refer.",
  alternates: { canonical: "/partners" },
};

const regulatorCount = new Set(brokers.flatMap((b) => b.regulators)).size;

export default function PartnersPage() {
  const eligibleBrokers = cashbackPrograms
    .map((p) => getBrokerBySlug(p.brokerSlug))
    .filter((b): b is NonNullable<typeof b> => Boolean(b));

  return (
    <PartnerSmoothScroll>
      <main className="flex-1 bg-paper-high">
        <PartnerHero brokerCount={brokers.length} regulatorCount={regulatorCount} />

        <section id="how-it-works" className="scroll-mt-20">
          <div className="mx-auto max-w-4xl px-6 py-20 md:py-28">
            <Reveal>
              <span className="font-mono text-xs uppercase tracking-[0.25em] text-signal">
                How it works
              </span>
              <h2 className="mt-3 font-poppins text-3xl font-semibold text-text-dark md:text-4xl">
                From application to lifetime commissions
              </h2>
            </Reveal>
            <div className="mt-14">
              <StepTimeline />
            </div>
          </div>
        </section>

        <section className="bg-paper">
          <div className="mx-auto max-w-5xl px-6 py-20 md:py-28">
            <Reveal>
              <span className="font-mono text-xs uppercase tracking-[0.25em] text-signal">
                Commission calculator
              </span>
              <h2 className="mt-3 font-poppins text-3xl font-semibold text-text-dark md:text-4xl">
                See what your network could earn
              </h2>
            </Reveal>
            <div className="mt-12">
              <CommissionCalculator />
            </div>
          </div>
        </section>

        <section className="bg-ink text-text-on-ink">
          <div className="mx-auto grid max-w-6xl gap-12 px-6 py-20 md:py-28 lg:grid-cols-[1fr_460px] lg:items-center">
            <Reveal>
              <span className="font-mono text-xs uppercase tracking-[0.25em] text-signal">
                Partner dashboard
              </span>
              <h2 className="mt-3 max-w-lg font-poppins text-3xl font-semibold leading-tight md:text-4xl">
                Track every referral, commission, and payout in one place
              </h2>
              <p className="mt-5 max-w-md text-text-on-ink-muted">
                Once approved, you get access to your own partner dashboard —
                separate from ours — showing referral activity, commission
                earned, and payout status.
              </p>
            </Reveal>
            <Reveal delay={150}>
              <TiltWrapper>
                <PartnerDashboardPreview />
              </TiltWrapper>
            </Reveal>
          </div>
        </section>

        <section>
          <div className="mx-auto max-w-6xl px-6 py-20 md:py-28">
            <Reveal>
              <span className="font-mono text-xs uppercase tracking-[0.25em] text-signal">
                Partner levels
              </span>
              <h2 className="mt-3 font-poppins text-3xl font-semibold text-text-dark md:text-4xl">
                Grow into a higher tier as your network grows
              </h2>
            </Reveal>
            <div className="mt-12">
              <PartnerTierCards />
            </div>
          </div>
        </section>

        <section className="bg-paper">
          <div className="mx-auto max-w-6xl px-6 py-20 md:py-28">
            <Reveal>
              <span className="font-mono text-xs uppercase tracking-[0.25em] text-signal">
                Why FXPARTNER
              </span>
              <h2 className="mt-3 font-poppins text-3xl font-semibold text-text-dark md:text-4xl">
                Built for people who bring real audiences
              </h2>
            </Reveal>
            <div className="mt-12">
              <WhyFxPartner />
            </div>
          </div>
        </section>

        <section>
          <div className="mx-auto max-w-4xl px-6 py-20 md:py-28">
            <Reveal>
              <span className="font-mono text-xs uppercase tracking-[0.25em] text-signal">
                Content, made for you
              </span>
              <h2 className="mt-3 font-poppins text-3xl font-semibold text-text-dark md:text-4xl">
                Never run out of things to share
              </h2>
            </Reveal>
            <div className="mt-10">
              <ContentStudioPreview />
            </div>
            <div className="mt-14">
              <ContentLibraryTeaser />
            </div>
          </div>
        </section>

        <section className="bg-paper">
          <div className="mx-auto max-w-5xl px-6 py-20 md:py-28">
            <Reveal>
              <span className="font-mono text-xs uppercase tracking-[0.25em] text-signal">
                Global network
              </span>
              <h2 className="mt-3 font-poppins text-3xl font-semibold text-text-dark md:text-4xl">
                Partners, spanning every region
              </h2>
            </Reveal>
            <div className="mt-10">
              <GlobalNetworkMap />
            </div>
          </div>
        </section>

        <section>
          <div className="mx-auto max-w-3xl px-6 py-16">
            <h2 className="font-poppins text-2xl font-semibold text-text-dark">
              Brokers with an active partner agreement
            </h2>
            <p className="mt-3 max-w-xl text-sm leading-relaxed text-text-muted">
              Sub-IB partnerships are currently available for the brokers
              below, where FXPARTNER already has a confirmed master IB
              agreement in place. Let us know your preference in the
              application — we&apos;ll confirm feasibility and exact terms
              with the broker directly.
            </p>
            <div className="mt-8 divide-y divide-hairline-light border-t border-hairline-light">
              {eligibleBrokers.map((broker) => (
                <div
                  key={broker.slug}
                  className="flex flex-wrap items-baseline justify-between gap-3 py-5"
                >
                  <h3 className="font-poppins text-lg font-semibold text-text-dark">
                    {broker.name}
                  </h3>
                  <Link
                    href={`/brokers/${broker.slug}`}
                    className="font-mono text-xs uppercase tracking-[0.15em] text-text-muted transition-colors hover:text-text-dark"
                  >
                    Full review →
                  </Link>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="bg-paper">
          <div className="mx-auto max-w-3xl px-6 py-16">
            <h2 className="font-poppins text-2xl font-semibold text-text-dark">
              Who this is for
            </h2>
            <ul className="mt-6 space-y-3 text-sm leading-relaxed text-text-muted">
              <li>— You run a social media account, YouTube channel, or blog with an audience interested in trading.</li>
              <li>— You manage a trading signal group, community, or Telegram channel.</li>
              <li>— You already refer traders informally and want a proper, trackable partner setup instead.</li>
              <li>— You run a business or network where forex broker referrals are a natural fit.</li>
            </ul>
            <p className="mt-6 text-xs leading-relaxed text-text-muted">
              This is not investment advice, and it is not a guaranteed income
              opportunity — actual earnings depend entirely on the trading
              volume of clients you refer and each broker&apos;s final
              approval and terms. FXPARTNER does not accept applications
              intended to spam, mislead, or misrepresent the broker to
              potential clients.
            </p>
          </div>
        </section>

        <section>
          <div className="mx-auto max-w-3xl px-6 py-20 md:py-28">
            <Reveal>
              <span className="font-mono text-xs uppercase tracking-[0.25em] text-signal">
                FAQ
              </span>
              <h2 className="mt-3 font-poppins text-3xl font-semibold text-text-dark md:text-4xl">
                Common questions
              </h2>
            </Reveal>
            <div className="mt-10">
              <PartnerFAQ />
            </div>
          </div>
        </section>

        <section className="relative overflow-hidden bg-ink text-text-on-ink">
          <div
            aria-hidden="true"
            className="hero-glow-signal pointer-events-none absolute -left-24 top-1/3 h-[420px] w-[420px] rounded-full bg-signal/25 blur-[110px]"
          />
          <div
            aria-hidden="true"
            className="hero-glow-gold pointer-events-none absolute -right-16 bottom-0 h-[360px] w-[360px] rounded-full bg-gold/20 blur-[110px]"
          />
          <div className="relative mx-auto max-w-3xl px-6 py-24 text-center md:py-32">
            <Reveal>
              <div className="relative mx-auto overflow-hidden rounded-3xl border border-hairline bg-ink-soft/60 px-8 py-14 backdrop-blur-sm">
                <div
                  aria-hidden="true"
                  className="glass-shimmer pointer-events-none absolute inset-y-0 left-0 w-1/3 skew-x-[-20deg] bg-gradient-to-r from-transparent via-white/10 to-transparent"
                />
                <h2 className="font-display text-3xl font-semibold leading-tight tracking-tight md:text-5xl">
                  Start building your partner business today.
                </h2>
                <p className="mx-auto mt-5 max-w-xl text-text-on-ink-muted">
                  Apply once, get matched with a broker&apos;s partner desk,
                  and start earning lifetime commissions on the traders you
                  bring in.
                </p>
                <a
                  href="#apply"
                  className="lift-on-hover mt-9 inline-block rounded-full bg-signal px-8 py-3.5 text-sm font-medium text-on-signal transition-colors hover:bg-signal-strong hover:shadow-lg hover:shadow-signal/30"
                >
                  Become a Partner
                </a>
              </div>
            </Reveal>
          </div>
        </section>

        <section id="apply" className="bg-paper scroll-mt-20">
          <div className="mx-auto max-w-2xl px-6 py-16">
            <h2 className="font-poppins text-2xl font-semibold text-text-dark">
              Apply as a partner
            </h2>
            <p className="mt-3 text-sm leading-relaxed text-text-muted">
              Fill in the form below and our partnerships team will follow up
              by email.
            </p>
            <div className="mt-8">
              <PartnerApplicationForm
                brokers={eligibleBrokers.map((b) => ({ slug: b.slug, name: b.name }))}
              />
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </PartnerSmoothScroll>
  );
}
