// Editorial content for the /partners page. Kept separate from brokers.ts
// since this is partner-program copy, not broker review data. Any figures
// here (tier thresholds, rev-share percentages, calculator rate) are
// illustrative examples, not confirmed broker terms — every section that
// surfaces a number pulled from here also carries a disclaimer saying so.

export interface PartnerStep {
  title: string;
  body: string;
}

export const partnerSteps: PartnerStep[] = [
  {
    title: "Register",
    body: "Apply in minutes with a few details about your audience and how you plan to introduce them to a broker. No cost, no commitment.",
  },
  {
    title: "Get your referral link",
    body: "Once approved, you receive your own Sub-IB tracking link under FXPARTNER's existing master IB agreement — no need to negotiate terms from scratch.",
  },
  {
    title: "Invite traders",
    body: "Share your link across your audience, community, or network — social media, Telegram, a blog, or word of mouth.",
  },
  {
    title: "Earn lifetime commissions",
    body: "Earn your agreed share of the rev-share generated by every client who signs up through your link and trades, for as long as they keep trading.",
  },
];

export interface PartnerTier {
  name: string;
  minReferred: number;
  revShareLabel: string;
  perks: string[];
}

// Illustrative tier structure only — final thresholds and rev-share are
// confirmed per broker agreement once a partner is approved.
export const partnerTiers: PartnerTier[] = [
  {
    name: "Bronze",
    minReferred: 1,
    revShareLabel: "Starting rev-share",
    perks: ["Personal referral link", "Monthly payout statement", "Email support"],
  },
  {
    name: "Silver",
    minReferred: 10,
    revShareLabel: "Increased rev-share",
    perks: ["Priority payout processing", "Access to the content library", "Dedicated partner ID"],
  },
  {
    name: "Gold",
    minReferred: 25,
    revShareLabel: "Higher rev-share tier",
    perks: ["Quarterly performance review", "Early access to new broker agreements", "Co-marketing opportunities"],
  },
  {
    name: "Diamond",
    minReferred: 50,
    revShareLabel: "Premium rev-share tier",
    perks: ["Dedicated partnerships contact", "Custom tracking links per campaign", "Priority broker introductions"],
  },
  {
    name: "Elite",
    minReferred: 100,
    revShareLabel: "Elite rev-share tier",
    perks: ["Direct line to the partnerships desk", "Input on upcoming broker partnerships", "Featured placement eligibility"],
  },
  {
    name: "Legend",
    minReferred: 250,
    revShareLabel: "Top negotiated rev-share",
    perks: ["Custom commercial terms", "Joint campaign planning", "Direct access to founder-level partnership discussions"],
  },
];

export interface WhyCard {
  key: "shield" | "rocket" | "graph" | "network" | "diamond";
  title: string;
  body: string;
}

export const whyFxPartnerCards: WhyCard[] = [
  {
    key: "shield",
    title: "Regulated broker network",
    body: "Every partner broker in our network already passed FXPARTNER's own review criteria — you're not referring traders into the unknown.",
  },
  {
    key: "rocket",
    title: "Fast, straightforward approval",
    body: "No lengthy onboarding. Apply, get matched with the broker's partner desk, and receive your link once approved.",
  },
  {
    key: "graph",
    title: "Transparent reporting",
    body: "Track referrals and commission activity through your own partner dashboard — separate from ours, controlled by you.",
  },
  {
    key: "network",
    title: "One agreement, multiple brokers",
    body: "Our master IB agreements mean you can extend into new broker partnerships without renegotiating terms every time.",
  },
  {
    key: "diamond",
    title: "A real partnerships desk",
    body: "Questions go to a dedicated partnerships contact, not a support queue — the same team that manages our own broker relationships.",
  },
];

export interface ContentLibraryCategory {
  title: string;
  description: string;
  itemCount: number;
}

export const contentLibraryCategories: ContentLibraryCategory[] = [
  { title: "Instagram templates", description: "Editable post and story layouts sized for feed and Reels.", itemCount: 18 },
  { title: "Telegram banners", description: "Channel headers and pinned-post graphics for trading communities.", itemCount: 12 },
  { title: "Reels & Shorts scripts", description: "Short-form video scripts you can record yourself or hand to an editor.", itemCount: 9 },
  { title: "Email swipe copy", description: "Ready-to-send email copy introducing your audience to partner brokers.", itemCount: 6 },
  { title: "Landing page assets", description: "Hero images and copy blocks for a simple referral landing page.", itemCount: 8 },
];

export interface ContentStudioSample {
  channel: string;
  preview: string;
}

export const contentStudioPrompt = "Create Instagram Post";

export const contentStudioSamples: ContentStudioSample[] = [
  {
    channel: "Instagram",
    preview: "\"Your trading network deserves better execution. Here's how to check if your broker actually delivers.\" — carousel, 5 slides",
  },
  {
    channel: "Telegram",
    preview: "📊 New partner spotlight — see which regulated brokers your community can access through your link.",
  },
  {
    channel: "Blog",
    preview: "\"What to look for in a forex broker before you refer your audience\" — 600-word draft, SEO title included.",
  },
  {
    channel: "Email",
    preview: "Subject: \"A referral link worth sharing\" — 3-paragraph draft for your newsletter.",
  },
];

export interface PartnerFaqItem {
  question: string;
  answer: string;
}

export const partnerFaqItems: PartnerFaqItem[] = [
  {
    question: "Is there a cost to join the partner program?",
    answer: "No. Applying and joining as a partner is free. There's no signup fee and no minimum spend requirement.",
  },
  {
    question: "Do I need to trade myself?",
    answer: "No. This program is for people who refer other traders, not for people trading their own account. If you're trading your own account, see our cashback program instead.",
  },
  {
    question: "How and when do I get paid?",
    answer: "Payout schedule and method are set by each broker's partner desk once you're approved as a Sub-IB — we'll confirm the specifics with you during onboarding.",
  },
  {
    question: "Which brokers can I partner with?",
    answer: "Sub-IB partnerships are currently available for the brokers where FXPARTNER already has a confirmed master IB agreement, listed further down this page.",
  },
  {
    question: "What happens if a referred client stops trading?",
    answer: "Commissions are generated by active trading volume. If a client stops trading, that client stops generating commission — there's no guaranteed or fixed income.",
  },
  {
    question: "How is this different from FXPARTNER's own affiliate relationship with brokers?",
    answer: "You get your own tracking link and your own agreement with the broker as a Sub-IB, separate from FXPARTNER's — your data and payouts are between you and the broker's partner desk.",
  },
];

export const calculatorDefaults = {
  referredTraders: 25,
  avgLotsPerTraderPerMonth: 4,
  commissionPerLot: 5,
};

export interface NetworkRegion {
  key: string;
  label: string;
  // Position expressed as a percentage of the panel's width/height, so the
  // layout stays a stylized network graphic rather than a literal (and
  // easy to get subtly wrong) world-map projection.
  x: number;
  y: number;
}

export const networkRegions: NetworkRegion[] = [
  { key: "europe", label: "Europe", x: 50, y: 22 },
  { key: "mena", label: "MENA", x: 58, y: 46 },
  { key: "asia-pacific", label: "Asia-Pacific", x: 82, y: 40 },
  { key: "africa", label: "Africa", x: 48, y: 68 },
  { key: "americas", label: "Americas", x: 16, y: 38 },
];

// Arcs are pairs of region keys from networkRegions above.
export const networkArcs: [string, string][] = [
  ["europe", "mena"],
  ["europe", "americas"],
  ["mena", "asia-pacific"],
  ["europe", "africa"],
  ["asia-pacific", "americas"],
];
